import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'en' | 'bn';

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'bookings': 'Bookings',
    'all_bookings': 'All Bookings',
    'create_booking': 'Create Booking',
    'bags': 'Bags',
    'create_bag': 'Create Bag',
    'receive_bag': 'Receive Bag',
    'received_bags': 'Received Bags',
    'admin': 'Admin',
    'branch_mapping': 'Branch Mapping',
    'operators': 'Operators',
    
    // Header & Profile
    'welcome_back': 'Welcome Back',
    'sign_in': 'Sign In',
    'passport_booking': 'Passport Booking',
    'government_of_bangladesh': 'Government of Bangladesh',
    'profile': 'Profile',
    'settings': 'Settings',
    'preferences': 'Preferences',
    'help_support': 'Help & Support',
    'logout': 'Logout',
    'language': 'Language',
    'theme': 'Theme',
    'notifications': 'Notifications',
    'account_settings': 'Account Settings',
    'privacy': 'Privacy',
    'security': 'Security',
    'mark_all_read': 'Mark All Read',
    'notification_channels': 'Notification Channels',
    'all_notifications_read': 'All notifications read',
    'unread_notifications': 'unread notifications',
    'no_notifications': 'No notifications',
    'no_notifications_desc': 'You have no notifications at the moment.',
    'mark_as_read': 'Mark as read',
    'delete_notification': 'Delete notification',
    
    // Dashboard
    'total_bookings': 'Total Bookings',
    'todays_bookings': "Today's Bookings",
    'pending_verifications': 'Pending Verifications',
    'completed_deliveries': 'Completed Deliveries',
    'quick_actions': 'Quick Actions',
    'recent_activity': 'Recent Activity',
    'welcome_message': "Here's what's happening with your passport bookings today.",
    
    // Bookings
    'new_booking': 'New Booking',
    'booking_created': 'Booking Created Successfully!',
    'booking_updated': 'Booking Updated Successfully!',
    'application_id': 'Application ID',
    'full_name': 'Full Name',
    'phone_number': 'Phone Number',
    'fathers_name': "Father's Name",
    'mothers_name': "Mother's Name",
    'address': 'Address',
    'emergency_contact': 'Emergency Contact',
    'delivery_information': 'Delivery Information',
    'status': 'Status',
    'created': 'Created',
    'search_bookings': 'Search bookings...',
    'filters': 'Filters',
    'export': 'Export',
    'no_bookings_found': 'No bookings found',
    'booking_details': 'Booking Details',
    'applicant_information': 'Applicant Information',
    'status_timeline': 'Status Timeline',
    'edit_booking': 'Edit Booking',
    
    // Forms
    'create': 'Create',
    'update': 'Update',
    'save': 'Save',
    'cancel': 'Cancel',
    'submit': 'Submit',
    'search': 'Search',
    'required': 'Required',
    'optional': 'Optional',
    'loading': 'Loading...',
    'creating': 'Creating...',
    'updating': 'Updating...',
    'saving': 'Saving...',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'close': 'Close',
    'open': 'Open',
    'yes': 'Yes',
    'no': 'No',
    'confirm': 'Confirm',
    'success': 'Success',
    'error': 'Error',
    'warning': 'Warning',
    'info': 'Information',
    
    // Status
    'initial': 'Initial',
    'pre_booked': 'Pre-booked',
    'bagged': 'Bagged',
    'closed': 'Closed',
    'received': 'Received',
    'active': 'Active',
    'inactive': 'Inactive',
    
    // Common
    'name': 'Name',
    'phone': 'Phone',
    'email': 'Email',
    'date': 'Date',
    'time': 'Time',
    'description': 'Description',
    'details': 'Details',
    
    // Profile Pages
    'personal_information': 'Personal Information',
    'account_status': 'Account Status',
    'last_login': 'Last Login',
    'activity_summary': 'Activity Summary',
    'bookings_created': 'Bookings Created',
    'bags_processed': 'Bags Processed',
    'otps_verified': 'OTPs Verified',
    'success_rate': 'Success Rate',
    'edit_profile': 'Edit Profile',
    'save_changes': 'Save Changes',
    'full_address': 'Full Address',
    'department': 'Department',
    'join_date': 'Join Date',
    
    // Account Settings
    'password_security': 'Password & Security',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm New Password',
    'update_password': 'Update Password',
    'two_factor_auth': 'Two-Factor Authentication',
    'session_timeout': 'Session Timeout',
    'notification_preferences': 'Notification Preferences',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'push_notifications': 'Push Notifications',
    'system_information': 'System Information',
    'account_created': 'Account Created',
    'password_changed': 'Last Password Change',
    'login_sessions': 'Login Sessions',
    'data_usage': 'Data Usage',
    'deactivate_account': 'Deactivate Account',
    
    // Privacy
    'privacy_controls': 'Privacy Controls',
    'profile_visibility': 'Profile Visibility',
    'public': 'Public',
    'private': 'Private',
    'team_only': 'Team Only',
    'activity_tracking': 'Activity Tracking',
    'data_collection': 'Data Collection',
    'third_party_sharing': 'Third-party Sharing',
    'marketing_emails': 'Marketing Emails',
    'analytics_opt_out': 'Analytics Opt-out',
    'data_management': 'Data Management',
    'data_retention': 'Data Retention Periods',
    'export_data': 'Export My Data',
    'delete_all_data': 'Delete All Data',
    'privacy_rights': 'Your Privacy Rights',
    
    // Help & Support
    'contact_support': 'Contact Support',
    'phone_support': 'Phone Support',
    'email_support': 'Email Support',
    'live_chat': 'Live Chat',
    'faq': 'Frequently Asked Questions',
    'search_faqs': 'Search FAQs...',
    'submit_ticket': 'Submit Support Ticket',
    'ticket_subject': 'Subject',
    'ticket_category': 'Category',
    'ticket_priority': 'Priority',
    'ticket_message': 'Message',
    'submit_ticket_btn': 'Submit Ticket',
    
    // Bags
    'bag_information': 'Bag Information',
    'bag_category': 'Bag Category',
    'bag_type': 'Bag Type',
    'destination_office': 'Destination Office Code',
    'rms_instruction': 'RMS Instruction',
    'create_bag_success': 'Bag created successfully!',
    'add_item_to_bag': 'Add Item to Bag',
    'order_id': 'Order ID',
    'bag_id': 'Bag ID',
    'item_index': 'Index',
    'close_bag': 'Close Bag',
    'receive_bag_title': 'Receive Bag',
    'line_id': 'Line ID',
    'reception_instructions': 'Reception Instructions',
    'items_received': 'Items Received',
    'received_bags_title': 'Received Bags',
    'no_received_bags': 'No Received Bags',
    
    // Admin
    'system_operators': 'System Operators',
    'branch_mapping_title': 'Branch Mapping',
    'create_mapping': 'Create Branch Mapping',
    'username': 'Username',
    'branch_code': 'Branch Code',
    'relationship': 'Relationship',
    'primary': 'Primary',
    'secondary': 'Secondary',
    'search_branches': 'Search Branches',
    'no_operators': 'No Operators Found',
    
    // OTP
    'otp_verification': 'OTP Verification',
    'delivery_phone': 'Delivery Phone Number',
    'otp_code': 'OTP Code',
    'apply_otp': 'Apply OTP',
    'verify_otp': 'Verify',
    'resend_otp': 'Resend',
    'retry_info': 'Retry Info',
    'phone_verified': 'Phone number verified successfully!',
    'attempts_remaining': 'Attempts remaining',
    'otp_expires': 'OTP expires in',
    'today': 'Today at',
  },
  bn: {
    // Navigation
    'dashboard': 'ড্যাশবোর্ড',
    'bookings': 'বুকিং',
    'all_bookings': 'সব বুকিং',
    'create_booking': 'বুকিং তৈরি করুন',
    'bags': 'ব্যাগ',
    'create_bag': 'ব্যাগ তৈরি করুন',
    'receive_bag': 'ব্যাগ গ্রহণ করুন',
    'received_bags': 'প্রাপ্ত ব্যাগ',
    'admin': 'অ্যাডমিন',
    'branch_mapping': 'শাখা ম্যাপিং',
    'operators': 'অপারেটর',
    
    // Header & Profile
    'welcome_back': 'স্বাগতম',
    'sign_in': 'সাইন ইন',
    'passport_booking': 'পাসপোর্ট বুকিং',
    'government_of_bangladesh': 'বাংলাদেশ সরকার',
    'profile': 'প্রোফাইল',
    'settings': 'সেটিংস',
    'preferences': 'পছন্দসমূহ',
    'help_support': 'সাহায্য ও সহায়তা',
    'logout': 'লগআউট',
    'language': 'ভাষা',
    'theme': 'থিম',
    'notifications': 'বিজ্ঞপ্তি',
    'account_settings': 'অ্যাকাউন্ট সেটিংস',
    'privacy': 'গোপনীয়তা',
    'security': 'নিরাপত্তা',
    'mark_all_read': 'সব পড়া হিসেবে চিহ্নিত করুন',
    'notification_channels': 'বিজ্ঞপ্তি চ্যানেল',
    'all_notifications_read': 'সব বিজ্ঞপ্তি পড়া হয়েছে',
    'unread_notifications': 'অপঠিত বিজ্ঞপ্তি',
    'no_notifications': 'কোন বিজ্ঞপ্তি নেই',
    'no_notifications_desc': 'এই মুহূর্তে আপনার কোন বিজ্ঞপ্তি নেই।',
    'mark_as_read': 'পড়া হিসেবে চিহ্নিত করুন',
    'delete_notification': 'বিজ্ঞপ্তি মুছুন',
    
    // Dashboard
    'total_bookings': 'মোট বুকিং',
    'todays_bookings': 'আজকের বুকিং',
    'pending_verifications': 'অপেক্ষমাণ যাচাইকরণ',
    'completed_deliveries': 'সম্পন্ন ডেলিভারি',
    'quick_actions': 'দ্রুত কার্যক্রম',
    'recent_activity': 'সাম্প্রতিক কার্যকলাপ',
    'welcome_message': 'আজ আপনার পাসপোর্ট বুকিংয়ে কী ঘটছে তা এখানে।',
    
    // Bookings
    'new_booking': 'নতুন বুকিং',
    'booking_created': 'বুকিং সফলভাবে তৈরি হয়েছে!',
    'booking_updated': 'বুকিং সফলভাবে আপডেট হয়েছে!',
    'application_id': 'আবেদন আইডি',
    'full_name': 'পূর্ণ নাম',
    'phone_number': 'ফোন নম্বর',
    'fathers_name': 'পিতার নাম',
    'mothers_name': 'মাতার নাম',
    'address': 'ঠিকানা',
    'emergency_contact': 'জরুরি যোগাযোগ',
    'delivery_information': 'ডেলিভারি তথ্য',
    'status': 'অবস্থা',
    'created': 'তৈরি',
    'search_bookings': 'বুকিং খুঁজুন...',
    'filters': 'ফিল্টার',
    'export': 'রপ্তানি',
    'no_bookings_found': 'কোন বুকিং পাওয়া যায়নি',
    'booking_details': 'বুকিং বিস্তারিত',
    'applicant_information': 'আবেদনকারীর তথ্য',
    'status_timeline': 'অবস্থার সময়রেখা',
    'edit_booking': 'বুকিং সম্পাদনা',
    
    // Forms
    'create': 'তৈরি করুন',
    'update': 'আপডেট করুন',
    'save': 'সংরক্ষণ করুন',
    'cancel': 'বাতিল',
    'submit': 'জমা দিন',
    'search': 'খুঁজুন',
    'required': 'আবশ্যক',
    'optional': 'ঐচ্ছিক',
    'loading': 'লোড হচ্ছে...',
    'creating': 'তৈরি হচ্ছে...',
    'updating': 'আপডেট হচ্ছে...',
    'saving': 'সংরক্ষণ হচ্ছে...',
    'edit': 'সম্পাদনা',
    'delete': 'মুছুন',
    'view': 'দেখুন',
    'back': 'পিছনে',
    'next': 'পরবর্তী',
    'previous': 'পূর্ববর্তী',
    'close': 'বন্ধ',
    'open': 'খুলুন',
    'yes': 'হ্যাঁ',
    'no': 'না',
    'confirm': 'নিশ্চিত করুন',
    'success': 'সফল',
    'error': 'ত্রুটি',
    'warning': 'সতর্কতা',
    'info': 'তথ্য',
    
    // Status
    'initial': 'প্রাথমিক',
    'pre_booked': 'প্রি-বুকড',
    'bagged': 'ব্যাগড',
    'closed': 'বন্ধ',
    'received': 'প্রাপ্ত',
    'active': 'সক্রিয়',
    'inactive': 'নিষ্ক্রিয়',
    
    // Common
    'name': 'নাম',
    'phone': 'ফোন',
    'email': 'ইমেইল',
    'date': 'তারিখ',
    'time': 'সময়',
    'description': 'বিবরণ',
    'details': 'বিস্তারিত',
    
    // Profile Pages
    'personal_information': 'ব্যক্তিগত তথ্য',
    'account_status': 'অ্যাকাউন্টের অবস্থা',
    'last_login': 'শেষ লগইন',
    'activity_summary': 'কার্যকলাপের সারসংক্ষেপ',
    'bookings_created': 'তৈরি বুকিং',
    'bags_processed': 'প্রক্রিয়াকৃত ব্যাগ',
    'otps_verified': 'যাচাইকৃত ওটিপি',
    'success_rate': 'সফলতার হার',
    'edit_profile': 'প্রোফাইল সম্পাদনা',
    'save_changes': 'পরিবর্তন সংরক্ষণ',
    'full_address': 'সম্পূর্ণ ঠিকানা',
    'department': 'বিভাগ',
    'join_date': 'যোগদানের তারিখ',
    
    // Account Settings
    'password_security': 'পাসওয়ার্ড ও নিরাপত্তা',
    'current_password': 'বর্তমান পাসওয়ার্ড',
    'new_password': 'নতুন পাসওয়ার্ড',
    'confirm_password': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'update_password': 'পাসওয়ার্ড আপডেট করুন',
    'two_factor_auth': 'দ্বি-ফ্যাক্টর প্রমাণীকরণ',
    'session_timeout': 'সেশন টাইমআউট',
    'notification_preferences': 'বিজ্ঞপ্তি পছন্দ',
    'email_notifications': 'ইমেইল বিজ্ঞপ্তি',
    'sms_notifications': 'এসএমএস বিজ্ঞপ্তি',
    'push_notifications': 'পুশ বিজ্ঞপ্তি',
    'system_information': 'সিস্টেম তথ্য',
    'account_created': 'অ্যাকাউন্ট তৈরি',
    'password_changed': 'শেষ পাসওয়ার্ড পরিবর্তন',
    'login_sessions': 'লগইন সেশন',
    'data_usage': 'ডেটা ব্যবহার',
    'deactivate_account': 'অ্যাকাউন্ট নিষ্ক্রিয় করুন',
    
    // Privacy
    'privacy_controls': 'গোপনীয়তা নিয়ন্ত্রণ',
    'profile_visibility': 'প্রোফাইল দৃশ্যমানতা',
    'public': 'সর্বজনীন',
    'private': 'ব্যক্তিগত',
    'team_only': 'শুধুমাত্র দল',
    'activity_tracking': 'কার্যকলাপ ট্র্যাকিং',
    'data_collection': 'ডেটা সংগ্রহ',
    'third_party_sharing': 'তৃতীয় পক্ষের শেয়ারিং',
    'marketing_emails': 'মার্কেটিং ইমেইল',
    'analytics_opt_out': 'অ্যানালিটিক্স অপ্ট-আউট',
    'data_management': 'ডেটা ব্যবস্থাপনা',
    'data_retention': 'ডেটা ধরে রাখার সময়কাল',
    'export_data': 'আমার ডেটা রপ্তানি করুন',
    'delete_all_data': 'সব ডেটা মুছুন',
    'privacy_rights': 'আপনার গোপনীয়তার অধিকার',
    
    // Help & Support
    'contact_support': 'সহায়তার সাথে যোগাযোগ',
    'phone_support': 'ফোন সহায়তা',
    'email_support': 'ইমেইল সহায়তা',
    'live_chat': 'লাইভ চ্যাট',
    'faq': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
    'search_faqs': 'প্রশ্ন খুঁজুন...',
    'submit_ticket': 'সহায়তা টিকিট জমা দিন',
    'ticket_subject': 'বিষয়',
    'ticket_category': 'বিভাগ',
    'ticket_priority': 'অগ্রাধিকার',
    'ticket_message': 'বার্তা',
    'submit_ticket_btn': 'টিকিট জমা দিন',
    
    // Bags
    'bag_information': 'ব্যাগের তথ্য',
    'bag_category': 'ব্যাগের বিভাগ',
    'bag_type': 'ব্যাগের ধরন',
    'destination_office': 'গন্তব্য অফিস কোড',
    'rms_instruction': 'আরএমএস নির্দেশনা',
    'create_bag_success': 'ব্যাগ সফলভাবে তৈরি হয়েছে!',
    'add_item_to_bag': 'ব্যাগে আইটেম যোগ করুন',
    'order_id': 'অর্ডার আইডি',
    'bag_id': 'ব্যাগ আইডি',
    'item_index': 'সূচক',
    'close_bag': 'ব্যাগ বন্ধ করুন',
    'receive_bag_title': 'ব্যাগ গ্রহণ করুন',
    'line_id': 'লাইন আইডি',
    'reception_instructions': 'গ্রহণের নির্দেশনা',
    'items_received': 'প্রাপ্ত আইটেম',
    'received_bags_title': 'প্রাপ্ত ব্যাগসমূহ',
    'no_received_bags': 'কোন প্রাপ্ত ব্যাগ নেই',
    
    // Admin
    'system_operators': 'সিস্টেম অপারেটর',
    'branch_mapping_title': 'শাখা ম্যাপিং',
    'create_mapping': 'শাখা ম্যাপিং তৈরি করুন',
    'username': 'ব্যবহারকারীর নাম',
    'branch_code': 'শাখা কোড',
    'relationship': 'সম্পর্ক',
    'primary': 'প্রাথমিক',
    'secondary': 'মাধ্যমিক',
    'search_branches': 'শাখা খুঁজুন',
    'no_operators': 'কোন অপারেটর পাওয়া যায়নি',
    
    // OTP
    'otp_verification': 'ওটিপি যাচাইকরণ',
    'delivery_phone': 'ডেলিভারি ফোন নম্বর',
    'otp_code': 'ওটিপি কোড',
    'apply_otp': 'ওটিপি প্রয়োগ করুন',
    'verify_otp': 'যাচাই করুন',
    'resend_otp': 'পুনরায় পাঠান',
    'retry_info': 'পুনরায় চেষ্টার তথ্য',
    'phone_verified': 'ফোন নম্বর সফলভাবে যাচাই হয়েছে!',
    'attempts_remaining': 'অবশিষ্ট চেষ্টা',
    'otp_expires': 'ওটিপি মেয়াদ শেষ হবে',
    'today': 'আজ',
  },
};

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (language: Language) => set({ language }),
      t: (key: string) => {
        const { language } = get();
        return translations[language][key as keyof typeof translations.en] || key;
      },
    }),
    {
      name: 'passport-booking-language',
    }
  )
);